version: '3.9'

services:
  db:
    image: postgres:15
    container_name: fitcore-db
    environment:
      POSTGRES_USER: fitcore
      POSTGRES_PASSWORD: fitcore123
      POSTGRES_DB: fitcoredb
    ports:
      - "5432:5432" # проброс для доступа с хоста, внутри контейнера всё равно 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./fitcore-backend
    container_name: fitcore-backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=fitcoredb;Username=fitcore;Password=fitcore123"
      JWT_KEY: "SUPER_SECRET_KEY_123456789_1234567890"
    depends_on:
      - db

  frontend:
    build: ./fitcore-frontend
    container_name: fitcore-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
